### PR TITLE
New 268: Adding testcases for OAuth

### PR DESCRIPTION
**Pull request by alcastronic**
This PR covers issue #268 

- [x] This PR handles the issue and requires no additional PRs.
- [x] You have validated the need for this change.

### What did this PR accomplish

This PR adds new testing guidelines for the OAuth authorization framework to the OWASP Web Security Testing Guide. 

There are three documentes added to the section 05-Authorization_Testing with this PR. The README.md in this section is modified as well.

- [05-Authorization_Testing/README.md](https://github.com/alcastronic/wstg/blob/new-268/document/4-Web_Application_Security_Testing/05-Authorization_Testing/README.md) has three additions as three sections where added.
- [05-Authorization_Testing/05-Testing_for_OAuth_Weaknesses.md](https://github.com/alcastronic/wstg/blob/new-268/document/4-Web_Application_Security_Testing/05-Authorization_Testing/05-Testing_for_OAuth_Weaknesses.md) was added, describing how to identify and test OAuth architecture and desing decisions.
- [05-Authorization_Testing/05.1-Testing_for_OAuth_AS_Weaknesses.md](https://github.com/alcastronic/wstg/blob/new-268/document/4-Web_Application_Security_Testing/05-Authorization_Testing/05.1-Testing_for_OAuth_AS_Weaknesses.md) describing how to test different attacks against authorization servers
- [05-Authorization_Testing/05.2-Testing_for_OAuth_Client_Weaknesses.md](https://github.com/alcastronic/wstg/blob/new-268/document/4-Web_Application_Security_Testing/05-Authorization_Testing/05.2-Testing_for_OAuth_Client_Weaknesses.md) describing how to test different attacks against OAuth clients

### CODE REVIEW

**Comment by victoriadrake** [comment]
Will try to help out this weekend!

**Comment by victoriadrake** [comment]
@alcastronic Would you please consider allowing edits from maintainers as linked [here](https://github.com/OWASP/wstg/blob/master/CONTRIBUTING.md#how-to-submit-a-pull-request)? I've made some edits I've love to add!

**Comment by alcastronic** [comment]
@victoriadrake It seems that the checkbox for "Allow edits by maintainers" is set, does it work for you now?

image

**Comment by victoriadrake** [comment]
> @victoriadrake It seems that the checkbox for "Allow edits by maintainers" is set, does it work for you now?

It works! It may always have. I forgot to rename the branch when pushing. Thank you for checking!

**Comment by kingthorin** [comment]
We might have to come up with a replacement for humanstxt or drop it. There have been some other PRs where this was an issue, I had reached out and got no response :cry:

**Review by victoriadrake — APPROVED** [review]
Overall, this is a *great* addition! I really appreciate you taking the time to contribute!

I've done a copy edit pass and have some general feedback. I've already tidied up the specific points in these documents, so this is just for future use.

General feedback:

- Please link to sources or specification references where appropriate (inline citation) preferring RFCs over blog articles, YouTube, etc.
- Remember to write out acronyms for readers who may not be familiar, e.g. "JSON Web Token (JWT)"
- Use consistent capitalization to show when something is a proper term, e.g. "Implicit Flow" is referring to a specific flow, but "grant type" (no capitalization) isn't one particular thing
- Keep terms consistent to avoid confusion, e.g. you used "Authorization Code Grant" but called it just "Code Grant" and "code-grant" later.
- The "Test Objectives" statement should generally describe what the tests are for rather than what you need to do before a test. E.g., "Determine if deprecated OAuth methods are used." rather than "Assess whether the clients are confidential or public."

**Comment by alcastronic** [comment]
@victoriadrake Thanks you for the review and the improvements done to this document. It looks good to me now. I do appreciate your feedback, those are good points.

Is there anything I could do about the failed link check?

**Comment by kingthorin** [comment]
For the failed link you could look it up on the internet archive or wayback machine to see what kind of content was there and then maybe identify an alternative or decide if it's worth keeping.

**Comment by kingthorin** [comment]
I'll try to review the whole thing over the next week or so. Sorry for the delay, just in a busy period.

**Comment by alcastronic** [comment]
@kingthorin sure, whenever your time allows it.

**Review by kingthorin — APPROVED** [review]
Thanks!!

**Comment by kingthorin** [comment]
@alcastronic please open another PR adding yourself to the authors section: https://github.com/OWASP/wstg/blob/master/document/1-Frontispiece/README.md#authors

**Comment by kingthorin** [comment]
@alcastronic this might be of interest, or give you ideas for further content: https://www.linkedin.com/posts/owasp_next-week-on-owasp-devslop-farah-hawa-activity-6893221288815550464-THwR

**Comment by alcastronic** [comment]
> @alcastronic this might be of interest, or give you ideas for further content: https://www.linkedin.com/posts/owasp_next-week-on-owasp-devslop-farah-hawa-activity-6893221288815550464-THwR

Yes, I have that one on my timeline!

**Pull request merged**
