### PR TITLE
Tweak workflows to accommodate translation acitvities

### PR DESCRIPTION
**Pull request by kingthorin**
Fixes OWASP/wstg#671

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Review by ThunderSon — COMMENTED** [review]
By removing the translations directory, everything below will work just fine, no?

We don't remove the `.github` directory from the rest of the actions.

**Comment by kingthorin** [comment]
If the files are only in `translations/` the workflow won't run at all. If they're across directories (including `translations/`) it'll still run. We do exclude `.github` in some cases.

**Comment by rejahrehim** [comment]
We need to run the lint check in `translations/` for the commits form Gitlocalize. So excluding the whole folder from lint checker will skip the lint check too.
Is there any other options to check the integrity of the links in translations ?

**Comment by kingthorin** [comment]
Normal linting is being left for translations.

I'll check if there's a config that excludes local/internal link checking.

**Comment by kingthorin** [comment]
Are we clear and good in this now, can I go ahead with the merge?

**Comment by kingthorin** [comment]
Are we clear and good in this now, can I go ahead with the merge?

**Review by ThunderSon — APPROVED** [review]
Looks good from my side.

**Pull request merged**
