### PR TITLE
Fix Status column validation

### PR DESCRIPTION
**Pull request by ivanseidel**
This PR covers issue #923.

- [x] This PR handles the issue and requires no additional PRs.
- [x] You have validated the need for this change.

**What did this PR accomplish?**

- Excel checklist had a problem in the validation of Status column causing it to not autocomplete

Thank you for your contribution!

### CODE REVIEW

**Comment by kingthorin** [comment]
Please also update: https://github.com/OWASP/wstg/blob/master/checklist/README.md

**Comment by kingthorin** [comment]
https://www.virustotal.com/gui/url/5ac03992eff45dbc582189dc39494d079663a7b2234c7651c2d8c0694eb3b855?nocache=1

**Comment by ivanseidel** [comment]
Fixed README @kingthorin

**Comment by kingthorin** [comment]
The content itself has been updated to match 4.2?

**Comment by ivanseidel** [comment]
Actually, the name of the file already was 4.2, I guess that the pull request #645 did that, but didn't change the README.

**Review by kingthorin — COMMENTED** [review]
Thanks!

**Review by kingthorin — APPROVED** [review]

**Comment by ivanseidel** [comment]
Also @kingthorin, would an automated generated xlsx with an improved UI be a good addition to the project? Check the model I'm building: https://docs.google.com/spreadsheets/d/1TjQTYV7Zf167iGiz1V2fm2tk9RqwGfl0DYCRBVarK94/edit#gid=0

**Comment by kingthorin** [comment]
Absolutely. To be honest I hate maintaining that thing. If we can add a workflow similar to: https://github.com/OWASP/wstg/blob/master/.github/workflows/build-json.yml to build it that'd be wonderful. (Instead of frying to update the README with the checksum we could just publish it as another file and link it as `<filename.sha256>`.)

**Comment by ivanseidel** [comment]
that's what I was thinking. Will try to figure out something here, and open a new issue with pull request so we can discuss it

**Pull request merged**
