### PR TITLE
Appendix Re-org

### PR DESCRIPTION
**Pull request by kingthorin**
- Put all the files into one directory.
- Update all references (only appeared to be main README.md, and a single Appendix C references in document content).
- Modify 'latest' deploy job to handle the updated paths/naming.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by ThunderSon** [comment]
I believe the file names needs to follow the same header name, and we need a README for them?

**Comment by kingthorin** [comment]
I forgot the readme, @rejah did mention that.

**Comment by kingthorin** [comment]
And yes I’ll modify the L1 headings to align with the file names.

**Comment by kingthorin** [comment]
Thanks @ThunderSon

**Comment by kingthorin** [comment]
@rejahrehim would it help if the folder was `6-Appendix`?

**Comment by rejahrehim** [comment]
> @rejahrehim would it help if the folder was `6-Appendix`?

I have updated the script to work with the current state in #426 and #427. If we add `6-` we can remove one line from the script. 

Screenshot 2020-04-13 at 10 32 21 AM

Currently, added 6- from the script.

**Comment by ThunderSon** [comment]
I added an unrelated commit to this PR, forgiveness.

**Comment by kingthorin** [comment]
Will sort out the conflict shortly.

**Pull request merged**
