### PR TITLE
add tool: Pass Station

### PR DESCRIPTION
**Pull request by noraj**
~~This PR covers issue #<issue number>.~~

- [ ] This PR handles the issue and requires no additional PRs.
- [ ] You have validated the need for this change.

**What did this PR accomplish?**

Add a tool for default credentials

> CLI & library to search for default credentials among thousands of Products / Vendors

### CODE REVIEW

**Comment by kingthorin** [comment]
@noraj thanks for the contribution, however this isn't meant to be an exhaustive list and I'm not sure that adding a tool with less than a year of history and a single contributor does our readers/users justice.

I'll ask around the core team and get some more input.

**Comment by kingthorin** [comment]
@rbsec you just did an overhaul in this section, your input would be great as well.

**Comment by noraj** [comment]
@kingthorin should I add the default password lists listed [here](https://sec-it.github.io/pass-station/#/why) in the reference section?

**Comment by kingthorin** [comment]
If they're well established/maintained.

**Comment by rbsec** [comment]
I can't say that I've ever heard of Pass Station, but it's always interesting to learn about new tools. I am, however, always a little bit suspicious when someone submits a PR for their own tool without any real explanation of why it should be included compared to any alternatives.

Perhaps I'm just old fashioned, but I'm not really sure what the benefit of Pass Station is over just searching the [DefaultCreds-cheat-sheet CSV file](https://github.com/ihebski/DefaultCreds-cheat-sheet/blob/main/DefaultCreds-Cheat-Sheet.csv) with grep? That includes several of the advantages listed on the "why" page (such as case insensitive searching and highlighting the output) without the need for a Ruby project with ~40 dependencies, and also means that you'll have the latest version of the data (rather than having to wait unil you include the latest upstream).

Sure, it doesn't do fancy stuff like JSON or YAML output - but as a pentester do I really care? I'm not trying to write a new tool or build a whole automated system - I just want to quickly find what the default password for a Netgear switch is. Personally, if I saw that I need to install a tool and it's depenencies, when all I really want is the data, I'd just move on to the next link.

I think that the upstream CSV file that you use would be a good reference to add - but I'm not sure that Pass Station is mature enough, or adds enough on top of that to justify its inclusion.

Interested to hear other views.

**Comment by noraj** [comment]
> I can't say that I've ever heard of Pass Station, but it's always interesting to learn about new tools. I am, however, always a little bit suspicious when someone submits a PR for their own tool without any real explanation of why it should be included compared to any alternatives.
> 
> Perhaps I'm just old fashioned, but I'm not really sure what the benefit of Pass Station is over just searching the [DefaultCreds-cheat-sheet CSV file](https://github.com/ihebski/DefaultCreds-cheat-sheet/blob/main/DefaultCreds-Cheat-Sheet.csv) with grep? That includes several of the advantages listed on the "why" page (such as case insensitive searching and highlighting the output) without the need for a Ruby project with ~40 dependencies, and also means that you'll have the latest version of the data (rather than having to wait unil you include the latest upstream).
> 
> Sure, it doesn't do fancy stuff like JSON or YAML output - but as a pentester do I really care? I'm not trying to write a new tool or build a whole automated system - I just want to quickly find what the default password for a Netgear switch is. Personally, if I saw that I need to install a tool and it's depenencies, when all I really want is the data, I'd just move on to the next link.
> 
> I think that the upstream CSV file that you use would be a good reference to add - but I'm not sure that Pass Station is mature enough, or adds enough on top of that to justify its inclusion.
> 
> Interested to hear other views.

As I pentester I like to `cli-tool search stuff` from the CLI rather than opening a web browser googling for the github repository, opening the file, CTRL+F, next next next until I get the output or to wget the CSV file and never get it update as not packaged from anything. Also there are only 2 runtime dependencies and they can be mutualised with other tools. 

Ofc one submitting its own tool always looks like auto-promotion, but it's a FLOSS tool I have nothing to earn from it I was just saying myself that this could be useful to many peoples, and to answer about the alternatives you saw there were none by reading the why page.

**Pull request closed without merging**
