### PR TITLE
Add new cover image for version v4.2

### PR DESCRIPTION
**Pull request by rejahrehim**
- [x] This PR handles the issue and requires no additional PRs.
- [x] You have validated the need for this change.

**What did this PR accomplish?**

-  Add new cover image to align with #613

### CODE REVIEW

**Comment by ThunderSon** [comment]
Discussing a possible change to this. Stay tuned :)
_It's nothing major, don't worry haha_

**Comment by kingthorin** [comment]
@rejahrehim please continue, @ThunderSon means what I already mentioned via Slack.

**Comment by rejahrehim** [comment]
Updated OWASP logo with registered mark in all cover images @kingthorin @ThunderSon

**Review by kingthorin — APPROVED** [review]
Thanks!

**Review by ThunderSon — APPROVED** [review]
Thank you!

**Pull request merged**
