### PR TITLE
Update window exposure and use case images of chapter 2

### PR DESCRIPTION
**Pull request by anees264**
**What did this PR accomplish?**

- Updated Window of Vulnerability, Use and Misuse case images of chapter 2 
- Updated IMAP-SMTP-Injection image of chapter 4

### CODE REVIEW

**Comment by kingthorin** [comment]
Could you tweak the bottom element of this image just a bit?
image

**Comment by anees264** [comment]
> re: "Update IMAP-SMTP-Injection image of chapter 4" could you tweak the bottom element of this image just a bit?
> image

Sure! :)

**Comment by kingthorin** [comment]
Thanks!

**Comment by rejahrehim** [comment]
@anees264 Would it be possible to make the `Figure 4.7.10-1:Communication with the mail servers using the IMAP/SMTP Injection technique` horizontal like 
Screenshot 2020-04-07 at 9 04 17 AM

**Comment by ThunderSon** [comment]
For use and misuse case image:
- 3rd image in the application/server block, it should be `lock` instead of `look` account.
- The green and red arrows don't mean anything to a reader, as they don't know that you're mitigating or threatening. Can we be more clear in that? I don't mind the text, or maybe a small legend of what each means? Whichever you see best.
- Adding to the above point, the link between defender's actions vs attacker's actions is not really clear. The blue X green arrows are a bit confusing, especially that the blue one is crossing the whole page, and the other two are just small, direct.

As previously said, the design looks much better. We thank your contribution 😊

**Comment by ThunderSon** [comment]
For the Windows Exposure image:
- The vendor notifies `its` clients -- instead of `it's`
- The existence of the patch is widely known -- contains two white spaces before `widely`

**Comment by ThunderSon** [comment]
For the IMAP injection:
- `2'` doesn't mean anything to the reader by looking at the image. Could we create something, like a line going over the screen to signify that a bypass is happening?
- `2` and `3` if positioned below the green line will represent the green side better.

**Comment by ThunderSon** [comment]
Misuse image:
- The red side; it's missing the includes, because the threats don't point to anything if they don't contain each other.
- Mitigation, and not mitigate.

IMAP:
- Nothing major, lower case `Existence` and the fixed `its`

Thanks! 😄

**Comment by kingthorin** [comment]
@anees264 we're going to be adding another section to the credits. Probably "Artists" or "Graphics Contributors" (or something like that) could you let us know what name we should add?

**Comment by anees264** [comment]
@kingthorin Muhammed Anees is fine. thanks!

**Pull request merged**
