### PR TITLE
Migrate REST cheatsheet to WSTG

### PR DESCRIPTION
**Pull request by za**
GitHub issue: https://github.com/OWASP/wstg/issues/351

This PR covers issue #351 .

- [ ] This PR handles the issue and requires no additional PRs.
- [ ] You have validated the need for this change.

**What did this PR accomplish?**

- Point 1
- Point 2

Thank you for your contribution!

### CODE REVIEW

**Comment by kingthorin** [comment]
Various READMEs/ToCs should be updated to include the new doc.

**Comment by kingthorin** [comment]
The content should be revised to follow the WSTG [template](https://github.com/OWASP/wstg/tree/master/template)  and [style guide](https://github.com/OWASP/wstg/blob/master/style_guide.md)

**Comment by ThunderSon** [comment]
@kingthorin this was just the move from the CSS project to here, I diverted the conversation back to the issue: https://github.com/OWASP/wstg/issues/351

**Comment by kingthorin** [comment]
Instead of trying to place this when the conversation is still not done, I think I'll relocate it to root and just get this PR done.

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
