### PR TITLE
Update 01-Test_Network_Infrastructure_Configuration.md

### PR DESCRIPTION
**Pull request by jinsonvarghese**
**What did this PR accomplish?**

- Improved readability
- Fixed grammar mistakes

### CODE REVIEW

**Comment by jinsonvarghese** [comment]
> **The following mistakes were identified:**
> 
> /home/runner/work/wstg/wstg/document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/01-Test_Network_Infrastructure_Configuration.md 40:475 ✖ Incorrect usage of the term: “Internet”, use “internet” instead terminology

This is flagged from "Microsoft's Internet Information Server".

**Comment by kingthorin** [comment]
Just change it to IIS? (I feel that’s pretty universally understood)

**Comment by jinsonvarghese** [comment]
> Just change it to IIS? (I feel that’s pretty universally understood)

Agreed, done.

**Review by kingthorin — APPROVED** [review]
Thank you

**Pull request merged**
