### PR TITLE
Update README.md - Grammar

### PR DESCRIPTION
**Pull request by skovsgaard**
Minor grammatical correction

- [x] This PR handles the issue and requires no additional PRs.
- [x] You have validated the need for this change.

### CODE REVIEW

**Review by kingthorin — COMMENTED** [review]
Pretty sure infinite implies plural.

**Comment by skovsgaard** [comment]
> Pretty sure infinite implies plural. 

Pretty sure a sum defined as infinite is still a singular sum, grammatically speaking.

**Comment by rbsec** [comment]
This is one of those grammar questions that doesn't really have universally agreed answer (probably because English grammar is a complete mess).

The discussion on the English Language Stack Exchange [here](https://english.stackexchange.com/questions/5378/a-number-of-questions-has-been-or-have-been-asked) and [here](https://english.stackexchange.com/questions/5378/a-number-of-questions-has-been-or-have-been-asked) suggests that "are" is more correct, although there are about 5x as many results on Google for "There is an infinite number of" compared to "There are an infinite number of".

To me, "are" sounds more correct in that sentence, because the thing that we're talking about (ways that the an application can fail) is plural.

But TBH, I don't really care much either way - in both cases it's perfectly clear what the meaning is.

**Review by kingthorin — COMMENTED** [review]
If you want to change something here and drop "an" then it's all plural

**Pull request merged**
