### PR TITLE
Fixing typo in 09-04-Testing_for_Weak_Encryption

### PR DESCRIPTION
**Pull request by Bankde**
This PR covers issue #.

- [x] This PR handles the issue and requires no additional PRs.
- [x] You have validated the need for this change.

**What did this PR accomplish?**

fix the typo in content.

Thank you for your contribution!

### CODE REVIEW

**Comment by kingthorin** [comment]
https://dictionary.cambridge.org/dictionary/english/asymmetric

**Comment by Bankde** [comment]
Hi, the ECB is "symmetric encryption", not asymmetric.
Right now it's like saying RSA should not be used for symmetric encryption. It is not meaningful.

**Comment by rbsec** [comment]
This PR fixes a mistake in the content (which is good), but also introduces a bit of a grammatical error, as "in a symmetric encryption" isn't really a complete sentence. And leads to the confusion about whether that should be "a symmetric" or "asymmetric".

How about we just cut the sentence short and say `...is not suggested for use.` - because there's really very few cases where you should be using ECB at all, regardless of whether you're trying to do symmetric or some kind of weird asymmetric version of it?

**Comment by Bankde** [comment]
@rbsec thank you for the review. I agree with the better change.

**Review by rbsec — APPROVED** [review]

**Comment by kingthorin** [comment]
Thank you both!

**Comment by rbsec** [comment]
There's definitely a crypto-related version of the four candles/fork handles sketch to be made out of this.

**Pull request merged**
