### PR TITLE
Added new image for SDLC in Introduction

### PR DESCRIPTION
**Pull request by jishnurippon**

### CODE REVIEW

**Comment by kingthorin** [comment]
Could you let us know the source?

**Comment by jishnurippon** [comment]
> Could you let us know the source?

SDLC image re-created for wstg. I used CorelDRAW to create this image.

**Comment by kingthorin** [comment]
Thanks

**Comment by jishnurippon** [comment]
Recreated new images for chapter Introduction, The OWASP Testing Framework, and Web Application Security Testing.

**Comment by kingthorin** [comment]
Is there a reason you made the images executable? (755 vs 644)

**Comment by kingthorin** [comment]
Could you crop the wappalyzer image? There's little to no value in showing the entire window/page.

**Comment by jishnurippon** [comment]
> Is there a reason you made the images executable

To avoid document conflict, I use the same name and format for images.

**Comment by jishnurippon** [comment]
> Could you crop the wappalyzer image? There's little to no value in showing the entire window/page.

The image was cropped and the unwanted data was removed from the image.

**Comment by kingthorin** [comment]
> To avoid document conflict, I use the same name and format for images.

It shouldn't be an issue, git can keep track of changed binary files.

**Comment by jishnurippon** [comment]
> > To avoid document conflict, I use the same name and format for images.
> 
> It shouldn't be an issue, git can keep track of changed binary files.

Do I need to update all to Jpg ennu

**Comment by kingthorin** [comment]
> The image was cropped and the unwanted data was removed from the image.

Looks like you forgot to push the change.

**Comment by kingthorin** [comment]
> Do I need to update all in Jpg

No just revert the permission changes.

**Comment by kingthorin** [comment]
Is there enough contrast in the lower right? (The Develop part) Or, does it need a different font or different fill color?

image

**Comment by kingthorin** [comment]
The names don't need to change, just replace the files, git will take care of it.

Also the cropped wappalyzer image still isn't included.

If you're having problems let me know and I can update the PR.

**Comment by jishnurippon** [comment]
> Is there enough contrast in the lower right? (The Develop part) Or, does it need a different font or different fill color? The others seem fine to me, but I've gone back to look at it a number of times this morning and can't convince myself.
> 
> image

ok let me check

**Comment by jishnurippon** [comment]
> The names don't need to change, just replace the files, git will take care of it.
> 
> Also the cropped wappalyzer image still isn't included.
> 
> If you're having problems let me know and I can update the PR.

I update new images and keep old ones. The new upload will save a new name, and I've added the name to the MD file.

**Comment by jishnurippon** [comment]
> > Is there enough contrast in the lower right? (The Develop part) Or, does it need a different font or different fill color? The others seem fine to me, but I've gone back to look at it a number of times this morning and can't convince myself.
> > image
> 
> ok let me check

images updated please check @kingthorin

**Comment by kingthorin** [comment]
Looks wonderful thanks! I appreciate you working through this with me.

The only one I'm still hesitant about is the Wappalyzer one, I really think it could be trimmed down to just  be the relevant popup, or just the very top of the page where the popup shows (if you want to maintain a slice of the whole top just slightly larger than the popup).

**Comment by jishnurippon** [comment]
> Looks wonderful thanks! I appreciate you working through this with me.
> 
> The only one I'm still hesitant about is the Wappalyzer one, I really think it could be trimmed down to just be the relevant popup, or just the very top of the page where the popup shows (if you want to maintain a slice of the whole top just slightly larger than the popup).

At your suggestion, I resized the wappalyzer image and added a new image for the SMTP injection. Thank you for your valuable suggestion. @kingthorin

**Comment by kingthorin** [comment]
Could y0u oh update gh e dates in tyghdd Google file names? `20200406`

**Comment by kingthorin** [comment]
I pushed that fix, you'll need to fetch it and reset.
```
git fetch origin
git reset --hard origin/feature-image-update
```

Then you can update further on top.

Could you tweak the red words to have leading caps (so that everything is in Title Caps):
image

**Comment by jishnurippon** [comment]
> I pushed that fix, you'll need to fetch it and reset. (The following assumes you're in the repo directory and on the feature/PR branch.)
> 
> ```
> git fetch origin
> git reset --hard origin/feature-image-update
> ```
> 
> Then you can update further on top.
> 
> Could you tweak the red words to have leading caps (so that everything is in Title Caps):
> image

I updated all the characters you mentioned in the picture. @kingthorin

**Comment by kingthorin** [comment]
@jishnurippon we're going to be adding another section to the credits. Probably "Artists" or "Graphics Contributors" (or something like that) could you let us know what name we should add?

https://github.com/OWASP/wstg/tree/master/document/1-Frontispiece

**Comment by jishnurippon** [comment]
> @jishnurippon we're going to be adding another section to the credits. Probably "Artists" or "Graphics Contributors" (or something like that) could you let us know what name we should add?
> 
> https://github.com/OWASP/wstg/tree/master/document/1-Frontispiece

Hi my name is <b>JISHNU VIJAYAN C K @kingthorin

**Comment by kingthorin** [comment]
Thanks!

**Pull request merged**
