### PR TITLE
textlint: Handle "client-" and "server-" side terms

### PR DESCRIPTION
**Pull request by kingthorin**
This PR closes OWASP/wstg#494.

- [x] This PR handles the issue and requires no additional PRs.
- [x] You have validated the need for this change.

* Per twitter and slack polls, the community has voted and settled on the hyphenated variants.
image

image

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
I believe this is ready for review.

**Comment by kingthorin** [comment]
Addressed.

**Comment by ThunderSon** [comment]
Just before accepting, this will change the names of some files (client-side), so about that ... The textlint was conducted on the files prior to that, the URL that were changed to client-side instead of client_side work. What about later usage of the linter? A bit confusing.

**Comment by kingthorin** [comment]
File names were changed manually. Future instances (if any) we'll have to catch during PR review.

**Comment by kingthorin** [comment]
This content has been deployed and all seems good: https://github.com/OWASP/www-project-web-security-testing-guide/pull/95

**Pull request merged**
