### PR TITLE
begin rewriting the WSTG-ATHN-02 guide

### PR DESCRIPTION
**Pull request by efx**
This PR covers issue #564 .

- [x] This PR handles the issue and requires no additional PRs.
- [x] You have validated the need for this change.

**What did this PR accomplish?**

- rewrote summary for clarity and brevity

I hope to polish more of the document throughout today.

Thank you for your contribution!

### CODE REVIEW

**Comment by efx** [comment]
@ThunderSon The PR is ready for your or other maintainers review. I removed most of the content for two reasons:
1. It duplicated other guides.
1. The wording was especially disheveled and unclear. After reading the style guide I opted towards brutally terse. We can  always build up should more context be needed. 

For my first pass I felt like keeping the guide focused on 1 topic was appropriate. The steps are still quite abstract.

**Comment by ThunderSon** [comment]
Hello @efx . This is a bit on hold as we're taking care of the 4.2 release. We'll discuss this and review it just after the release :)

**Comment by ThunderSon** [comment]
Looking at what was accomplished, do you feel like this could be part of the other guides?
So instead of cleaning this up, we merge its content with the other 2 guides.

Let me know what you think.

**Comment by efx** [comment]
@ThunderSon Pruning left this document quite bare! I agree it could be merged with another document. Could you provide additional guidance on what you expected? I'm happy to move these revisions into the single document and then delete this file.

**Comment by ThunderSon** [comment]
@kingthorin what do you think? I feel like default credentials are part of pass policies and enumerating "known" (defaults most of the times) users.

**Comment by kingthorin** [comment]
Seems reasonable to me.

**Comment by ThunderSon** [comment]
@efx I will close this PR. Please let's do as discussed in a new PR. I will update the issue to reflect on our discussion.

**Comment by efx** [comment]
@ThunderSon sounds good. Can you detail what you expect in that ticket? If that proves too much, I would rather you assign the ticket to yourself since it sounds like you have a clearer idea of what to change and how. Otherwise I'm happy to revise my approach.

**Pull request closed without merging**
