### PR TITLE
Update file name for github action and restrict to run only  on MD files

### PR DESCRIPTION
**Pull request by rejahrehim**
- [x] This PR handles the issue and requires no additional PRs.
- [x] You have validated the need for this change.

**What did this PR accomplish?**

- Update the file name to a more meaningful one
- Restrict the lint check to run only a markdown file change pushed

### CODE REVIEW

**Comment by rejahrehim** [comment]
@ThunderSon Need to update the required actions based on the name change

**Comment by kingthorin** [comment]
We will have to temporarily remove the requirement to merge this. Then have to reset the setting after it's used (after merge).

**Comment by kingthorin** [comment]
Just to be clear, specifying the path component doesnt restrict that this is only run on md files, but does mean that if the PR doesn't include md5 it will be skipped. Ex: in a PR with mixed files that does include md5 it'll still run on non-md files.

**Comment by kingthorin** [comment]
As we are discovering with the link check, is this needed on `push`? If so the `branches` and `paths` details should be the same.

**Comment by rejahrehim** [comment]
> As we are discovering with the link check, is this needed on `push`? If so the `branches` and `paths` details should be the same.

Yup, As we are only checking those while PRs we can remove the `push`

**Pull request merged**
