### PR TITLE
corrected Burp extension name

### PR DESCRIPTION
**Pull request by tavdog**
- [x] This PR handles the issue and requires no additional PRs.
- [x] You have validated the need for this change.

**What did this PR accomplish?**

- changed Authorize to Autorize

### CODE REVIEW

**Comment by kingthorin** [comment]
Blocked until after v4.1.

**Comment by kingthorin** [comment]
No longer blocked. Is not conflicting due to the EOL consistency changes. I'll address the conflict and push an update.

**Comment by victoriadrake** [comment]
I think this may be invalid: is “Autorize” correct? https://github.com/Quitten/Autorize

If yes, we ought to add a link.

**Comment by kingthorin** [comment]
Authorize is correct, linkify’ing is a good move.

**Comment by ThunderSon** [comment]
Not really worried about links right now. This whole test is nowhere near finished.

**Pull request merged**
