### PR TITLE
Fix "Wapplyzer" Typo

### PR DESCRIPTION
**Pull request by jinsonvarghese**
Fixed the spelling error.

### CODE REVIEW

**Comment by jinsonvarghese** [comment]
> **The following links are broken:** FILE:document/4-Web_Application_Security_Testing/01-Information_Gathering/08-Fingerprint_Web_Application_Framework.md [✖] #Remediation → Status: 404 [✖] #Cookies → Status: 404

Not sure what the issue is here.

**Comment by kingthorin** [comment]
Looks like there are some fragment/anchor links that should use lowercase.

**Comment by jinsonvarghese** [comment]
@kingthorin Thanks. This is done.

**Review by kingthorin — APPROVED** [review]
Thanks!

**Pull request merged**
