### PR TITLE
Retire RIA content & Link Check Fixes

### PR DESCRIPTION
**Pull request by kingthorin**
- [ ] This PR handles the issue and requires no additional PRs.
- [x] You have validated the need for this change.

* 01-Conduct_Search_Engine_Discovery_Reconnaissance_for_Information_Leakage > Remove start page references.
* 04-Enumerate_Applications_on_Webserver > Switch domaintools to mxtoolbox (the former was 404'ing). Add an oxford comma.
* 08-Test_RIA_Cross_Domain_Policy > Remove content (leave placeholder as we've done elsewhere), both Flash and SIlverlight are well beyond EOL.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
The link check 403 is a false positive.

**Review by ThunderSon — APPROVED** [review]
LGTM!

**Comment by ThunderSon** [comment]
@kingthorin can you in the merge add a note of why this was retired as the main commit message? Just to ensure it's well mentioned in the change log

**Comment by kingthorin** [comment]
Yup, will do

**Pull request merged**
