### PR TITLE
Checklist README tweaks for v4.1

### PR DESCRIPTION
**Pull request by kingthorin**
- Add reference to markdown checklist (which does have v4.1 updates).
- Clarify elements that pertain to the Excel checklist.

### CODE REVIEW

**Comment by kingthorin** [comment]
To?

**Comment by jespunya** [comment]
In my opinion it should include the release version number.

**Comment by kingthorin** [comment]
That's seems reasonable/logical for the excel file. 

For the markdown file it is likely to be "latest" or "live". (We could consider rolling it at release.)

**Comment by jespunya** [comment]
Yes, I was thinking just about the .xlsx

**Pull request merged**
