### PR TITLE
rephrased the question

### PR DESCRIPTION
**Pull request by rishuranjanofficial**
This PR covers issue #<issue number>.

- [x] This PR handles the issue and requires no additional PRs.
- [ ] You have validated the need for this change.

**What did this PR accomplish?**

- Rephrased the grammatically correct question. 

Thank you for your contribution!

### CODE REVIEW

**Comment by kingthorin** [comment]
This seems to be a matter of perspective. If it's something the team has to do then the wording s correct, if it's something the submitter is going to do then the modification is correct.

The existing wording seems more generic to me.

**Comment by ThunderSon** [comment]
Yes the existing one covers both possibilities, whereas the proposed change says clearly that the issue author will create a PR for this.

**Comment by rishuranjanofficial** [comment]
Hi Kingthorin and ThunderSon,

Thanks for the swift comment. The sentence is making sense and can be understood. But, the following sentence is grammatically incorrect.

Sentence in new-content.md - **What would you like added?**

It should be - **What would you like **to be** added?**

The above modified sentence also cover both the perspective. You can close this PR, if you still think the present sentence is appropriate. 

I would like to contribute more. Right now, I am going through the present Repo and will let you know if any change(s) is(are) required. Soon, I would like to add more content and scripts to automate the controls. Thanks in advance.

**Comment by kingthorin** [comment]
> It should be - What would you like to be added?

I think we're going to have to agree to disagree. Perhaps "What would you like to have added?" However, it's still fine as it currently is.

**Comment by rishuranjanofficial** [comment]
Hi Kingthorin,

Thanks again for your revert. It's Fine now. :+1:

**Pull request closed without merging**
