### PR TITLE
Typo Fix 06-Identify_Application_Entry_Points.md:23 

### PR DESCRIPTION
**Pull request by matsch92**
This PR covers issue #<issue number>.

- [x] This PR handles the issue and requires no additional PRs.
- [x] You have validated the need for this change.

**What did this PR accomplish?**

- Fixes a Typo on file `06-Identify_Application_Entry_Points.md` line 23

Thank you for your contribution!

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by smodnix** [comment]
Please update it for `www-project-web-security-testing-guide` too.

**Comment by kingthorin** [comment]
@smodnix I don't see any occurrence of "WebSockers" on https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/01-Information_Gathering/06-Identify_Application_Entry_Points

**Comment by smodnix** [comment]
Hey @kingthorin,
I meant stable version, sorry for misunderstanding. 

Thank you

**Comment by kingthorin** [comment]
No problem. I’d rather people ask 🙂

**Pull request merged**
