### PR TITLE
Add Test for Content Security Policy

### PR DESCRIPTION
**Pull request by phish**
This PR covers issue #654 .

- If this pull request is accepted, the various tables of contents need to be adjusted. 

I have created test 12 in chapter 02-Configuration_and_Deployment_Management_Testing.

It describes the rationale about the Content Security Policy header and explains how to test for it.

### CODE REVIEW

**Comment by kingthorin** [comment]
Note, I'm not sure how this happened. But, someone already tackled introducing CSP content in: https://github.com/OWASP/wstg/pull/708

Let's get that one merged then you can add some of this content to that?

**Comment by phish** [comment]
Yes, OK for me

Feb 4, 2021 12:22:32 AM Rick M <notifications@github.com>:

**Comment by ThunderSon** [comment]
@phish how about you review PR #708 with us and ensure that it's up to the level instead of having another PR?
I believe that'd be more in-line with how we're working. If you see anything that needs to be updated or added, just add a comment and set it on the PR :)

**Comment by phish** [comment]
I would be happy to help review PR #708

**Pull request closed without merging**
