### PR TITLE
Adjust refresh-stale to run once a month

### PR DESCRIPTION
**Pull request by kingthorin**
On the 15th at midnight.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by ThunderSon** [comment]
Can we possibly do it bi-weekly? 14 days is a much better period. I've never seen anything get resolved in 7 days (unless we're tackling it head on)

**Comment by kingthorin** [comment]
Unfortunately no, the next step would have to be once a month.

**Comment by ThunderSon** [comment]
I'd say every month is more sensible every week, unless we go on some mad mode.

**Comment by kingthorin** [comment]
Changed

**Pull request merged**
