### PR TITLE
Update 09-Test_Upload_of_Malicious_Files.md

### PR DESCRIPTION
**Pull request by 0xmaximus**
add additional check for image files.
Check for maximum pixel size.

This PR covers issue #1018.

- [ ] This PR handles the issue and requires no additional PRs.
- [x] You have validated the need for this change.

**What did this PR accomplish?**

Adding Test for oversized image file upload

### CODE REVIEW

**Comment by kingthorin** [comment]
> **The following mistakes were identified:**
> 
> /home/runner/work/wstg/wstg/document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md 15:253 
> ✖ Incorrect usage of the term: “IDS”, use “IDs” instead terminology 76:36 

I'd suggest switching it to: ` Intrusion Detection/Prevention System, application server anti-virus software or anti-virus scanning by application as files are uploaded ...`

> ✖ Incorrect usage of the term: “file names”, use “filenames” instead terminology

Sure this can be switched as outlined.

**Comment by kingthorin** [comment]
The linkcheck result is a false positive.

**Comment by kingthorin** [comment]
The terminology lint issue still needs to be addressed as outlined earlier. I know it’s not content you changed but it should be fixed since the linter picked it up. (Leave things better than you found them kind of philosophy.)

**Review by kingthorin — CHANGES_REQUESTED** [review]
The terminology lint issue still needs to be addressed as outlined earlier. I know it’s not content you changed but it should be fixed since the linter picked it up. (Leave things better than you found them kind of philosophy.)

**Review by kingthorin — APPROVED** [review]

**Comment by 0xmaximus** [comment]
Done, Thanks

**Pull request merged**
