### PR TITLE
chore: Update Testing Tools Resource (Appendix A)

### PR DESCRIPTION
**Pull request by kingthorin**
This PR is a follow-up to OWASP/wstg#901.

- Drop w3af which seems to no longer be maintained.
- Add Ffuf.
- Add Nuclei.
- Add ZAP to "Remote Brute Force"

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
@jinsonvarghese seem reasonable?

**Comment by ThunderSon** [comment]
Should we rely on something like [this](https://owasp.org/www-community/api_security_tools)?
Maybe we can abstract this for all of owasp and then link to those? What do you think?

**Comment by jinsonvarghese** [comment]
> @jinsonvarghese does this seem reasonable/good?

@kingthorin yes, this looks good.

**Comment by kingthorin** [comment]
> Should we rely on something like [this](https://owasp.org/www-community/api_security_tools)?
> Maybe we can abstract this for all of owasp and then link to those? What do you think?

That’s kinda bigger or more involved than I was shooting for here but definitely worth some thought/investigation.

**Pull request merged**
