### PR TITLE
Typo in SQLi Test

### PR DESCRIPTION
**Pull request by Nima-Dabbaghi**
This PR covers issue #<issue number>.

- [x] This PR handles the issue and requires no additional PRs.
- [ ] You have validated the need for this change.

**What did this PR accomplish?**

- This misspelling must be corrected

Thank you for your contribution!
Assign me, please!

### CODE REVIEW

**Comment by kingthorin** [comment]
Please address the conflict.

**Comment by Nima-Dabbaghi** [comment]
> Please address the conflict.

[](https://postimg.cc/9Rc8xP9Q)

**Comment by kingthorin** [comment]
Yes but you also pushed another change which is causing a conflict because it's for something that's already been addressed.

**Comment by Nima-Dabbaghi** [comment]
> Yes but you also pushed another change which is causing a conflict because it's for something that's already been addressed.

If you remember, yesterday I reported the problem of converting * to / * in the commenting . That is for it. Nothing more
[](https://postimg.cc/5QXcxcmr)

**Comment by kingthorin** [comment]
Already done.

**Comment by ThunderSon** [comment]
The issue you're discussing has been tackled and closed in #679 
I will merge this to fix the `our` typo.

**Review by ThunderSon — APPROVED** [review]

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
Thanks @Nima-Dabbaghi and @ThunderSon!

**Comment by Nima-Dabbaghi** [comment]
Thanks @ThunderSon

**Pull request merged**
